oop_web/app/views/article_views.py
from flask import Blueprint, render_template, request
from app.models import Article, Comment
from app.keyword2 import Keyword
from app.comment_filter import Comments
from app.rating import Rating

bp = Blueprint('article', __name__, url_prefix='/')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    article_list = Article.query.order_by(Article.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_event.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_list.html', article_list=article_list, page=page, kw=kw)

@bp.route('/detail/<int:article_id>/')
def detail(article_id):
    article = Article.query.get_or_404(article_id)
    keyword = ", ".join(Keyword(article).keyword_extract())
    com = []
    for i in article.comment_set:
        com.append(str(i.content))
    filter_com = Comments(com).prediction()
    return render_template('article/article_detail.html', article=article, keyword=keyword, filter_com=filter_com)

@bp.route('/category/politics/')
def politics():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.politics'
    cate = '정치'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/economics/')
def economics():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.economics'
    cate = '경제'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/international/')
def international():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.international'
    cate = '국제'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/social/')
def social():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.social'
    cate = '사회'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/culture/')
def culture():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.culture'
    cate = '문화'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/sports/')
def sports():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.sports'
    cate = '스포츠'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/press/')
def press():
    article_list = Article.query.order_by(Article.create_date.desc())
    press_list = ['한국일보', '중앙일보', 'MBC', '동아일보']
    dic = {}
    for press in press_list:
        press_type = '%%{}%%'.format(press)
        percent, LnD = Rating(article_list.filter(Article.type_of_press.ilike(press_type))).rating()
        dic[press] = [percent, LnD]
    return render_template('article/article_press.html',dic=dic)

oop_web/app/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return redirect(url_for('article._list'))

oop_web/app/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>News</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
{% block script %}
{% endblock %}
</body>
</html>

oop_web/app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">NewsCollector</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.politics') }}">정치</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.economics') }}">경제</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.international') }}">국제</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.social') }}">사회</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.culture') }}">문화</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.sports') }}">스포츠</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('article.press') }}">언론사평가</a>
                </li>
            </ul>
        </div>
    </div>
</nav>