oop_web/app/views/article_views.py
from flask import Blueprint, render_template, request
from app.models import Article, Comment
from app.keyword2 import Keyword
from app.comment_filter import Comments
from app.rating import Rating

bp = Blueprint('article', __name__, url_prefix='/')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    article_list = Article.query.order_by(Article.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_event.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_list.html', article_list=article_list, page=page, kw=kw)

@bp.route('/detail/<int:article_id>/')
def detail(article_id):
    article = Article.query.get_or_404(article_id)
    keyword = ", ".join(Keyword(article).keyword_extract())
    com = []
    for i in article.comment_set:
        com.append(str(i.content))
    filter_com = Comments(com).prediction()
    return render_template('article/article_detail.html', article=article, keyword=keyword, filter_com=filter_com)

@bp.route('/category/politics/')
def politics():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.politics'
    cate = '정치'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/economics/')
def economics():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.economics'
    cate = '경제'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/international/')
def international():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.international'
    cate = '국제'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/social/')
def social():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.social'
    cate = '사회'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/culture/')
def culture():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.culture'
    cate = '문화'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/category/sports/')
def sports():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    url = 'article.sports'
    cate = '스포츠'
    category = '%%{}%%'.format(cate)
    article_list = Article.query.order_by(Article.create_date.desc()).filter(Article.type_of_event.ilike(category))
    percent, LnD = Rating(article_list).rating()
    if kw:
        search = '%%{}%%'.format(kw)
        article_list = article_list.filter(
            Article.title.ilike(search) | Article.maintext.ilike(search) | Article.type_of_press.ilike(search)).distinct()
    article_list = article_list.paginate(page, per_page=10)
    return render_template('article/article_category.html', article_list=article_list, page=page, kw=kw, cate=cate,url=url, percent=percent, LnD=LnD)

@bp.route('/press/')
def press():
    article_list = Article.query.order_by(Article.create_date.desc())
    press_list = ['한국일보', '중앙일보', 'MBC', '동아일보']
    dic = {}
    for press in press_list:
        press_type = '%%{}%%'.format(press)
        percent, LnD = Rating(article_list.filter(Article.type_of_press.ilike(press_type))).rating()
        dic[press] = [percent, LnD]
    return render_template('article/article_press.html',dic=dic)

oop_web/app/templates/article/article_category.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{cate}}분야의 호불호: {{percent}}% - {{LnD}}</h2>
    <div class="row my-3">
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>호감도</th>
            <th>카테고리</th>
            <th>언론사</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if article_list %}
        {% for article in article_list.items %}
        <tr>
            <td>{{ article_list.total - ((article_list.page-1) * article_list.per_page) - loop.index0 }}</td>
            <td>
                <a href="{{ url_for('article.detail', article_id=article.id) }}">{{ article.title }}</a>
                {% if article.comment_set|length > 0 %}
                <span class="text-danger small mx-2">{{ article.comment_set|length }}</span>
                {% endif %}
            </td>
            <td>
                {% if article.likes == 0 %}
                0%
                {% else %}
                {{ (article.likes * 100 / (article.likes + article.dislikes)) |round|int}}%
                {% endif %}
            </td>
            <td>{{ article.type_of_event }}</td>
            <td>{{ article.type_of_press }}</td>
            <td>{{ article.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">기사가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if article_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ article_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in article_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != article_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ article_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<form id="searchForm" method="get" action="{{ url_for(url) }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

oop_web/app/templates/article/article_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 기사 -->
    <h2 class="border-bottom py-2">{{ article.title }}</h2>
    <h5 class="border-bottom my-3 py-2">언론사: {{ article.type_of_press }}  /  카테고리: {{ article.type_of_event }}</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ article.maintext }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ article.create_date|datetime }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">키워드: {{keyword}}</h5>
    <h5 class="border-bottom my-3 py-2">좋아요: {{article.likes}} / 싫어요: {{article.dislikes}}</h5>
    <!-- 댓글 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ article.comment_set|length }}개의 댓글이 있습니다.</h5>
    {% for com in filter_com %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ com }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

oop_web/app/templates/article/article_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>호감도</th>
            <th>카테고리</th>
            <th>언론사</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if article_list %}
        {% for article in article_list.items %}
        <tr>
            <td>{{ article_list.total - ((article_list.page-1) * article_list.per_page) - loop.index0 }}</td>
            <td>
                <a href="{{ url_for('article.detail', article_id=article.id) }}">{{ article.title }}</a>
                {% if article.comment_set|length > 0 %}
                <span class="text-danger small mx-2">{{ article.comment_set|length }}</span>
                {% endif %}
            </td>
            <td>
                {% if article.likes == 0 %}
                0%
                {% else %}
                {{ (article.likes * 100 / (article.likes + article.dislikes)) |round|int}}%
                {% endif %}
            </td>
            <td>{{ article.type_of_event }}</td>
            <td>{{ article.type_of_press }}</td>
            <td>{{ article.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">기사가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if article_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ article_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in article_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != article_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ article_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<form id="searchForm" method="get" action="{{ url_for('article._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

oop_web/app/templates/article/article_press.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom my-3 py-2">언론사 평가</h5>
    {% for key, value in dic.items() %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ key }}</div>
        </div>
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">호감도: {{ value[0] }}% - {{value[1]}}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}